- name: "Status: 🗯️ Waiting for feedback"
  from_name: "🗯️ Waiting for feedback"
  color: "f7d692"
- name: "Status: 🔴 Blocked"
  from_name: "🔴 Blocked"
  color: "f7d692"
  description: "Blocked by another issue or pull request"
- name: "Status: 🔒 After next release"
  from_name: "🔒 After next release"
  color: "f7d692"
  description: "Will be done after the next release"

- name: "Closed: ⚰️ Inactive"
  from_name: "⚰️ Inactive"
  color: "959a9c"
  description: "No answer was received for weeks"
- name: "Closed: 👥 Duplicate"
  from_name: "👥 Duplicate"
  color: "959a9c"
  description: "Issue duplicates an existing issue"
- name: "Closed: 🗑️ Bad issue"
  color: "959a9c"

- name: "Priority: 🚨 Urgent"
  from_name: "🚨 Urgent"
  color: "03adfc"
- name: "Priority: 💤 Low priority"
  from_name: "💤 Low priority"
  color: "03adfc"

- name: "Complexity: ☣️ Hard to do"
  from_name: "☣️ Hard to do"
  color: "ff9efc"
- name: "Complexity: 🟩 Easy to do"
  from_name: "🟩 Easy to do"
  color: "ff9efc"

- name: "Category: Config problem 📝"
  from_name: "Config problem"
  color: "ffc7ea"
- name: "Category: Shoutrrr 📢"
  from_name: "Shoutrrr"
  color: "ffc7ea"
- name: "Category: Healthcheck 🩺"
  from_name: "Healthcheck"
  color: "ffc7ea"
- name: "Category: Provider update ♻️"
  from_name: "Provider update"
  color: "ffc7ea"
- name: "Category: IP fetching 📥"
  from_name: "IP fetching"
  color: "ffc7ea"
- name: "Category: Database 🗃️"
  from_name: "Database"
  color: "ffc7ea"
- name: "Category: New provider 🆕"
  from_name: "New provider"
  color: "ffc7ea"
- name: "Category: Documentation ✒️"
  description: "A problem with the readme or in the docs/ directory"
  color: "ffc7ea"
- name: "Category: Maintenance ⛓️"
  description: "Anything related to code or other maintenance"
  color: "ffc7ea"
- name: "Category: Web UI 🖱️"
  color: "ffc7ea"
- name: "Category: Label missing ❗"
  color: "ffc7ea"
